//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemporaryGeneratedCode.MultiInheritance
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Linq;
    using NMF.Expressions;
    using NMF.Expressions.Linq;
    using NMF.Models;
    using NMF.Models.Meta;
    using NMF.Models.Collections;
    using NMF.Models.Expressions;
    using NMF.Collections.Generic;
    using NMF.Collections.ObjectModel;
    using NMF.Serialization;
    using NMF.Utilities;
    using NMF.Models.Repository;
    using System.Collections.Specialized;
    
    
    /// <summary>
    /// The default implementation of the Node class
    /// </summary>
    [XmlIdentifierAttribute("name")]
    [XmlNamespaceAttribute("http://example.com/multiInheritance")]
    [XmlNamespacePrefixAttribute("multiInheritance")]
    [ModelRepresentationClassAttribute("http://example.com/multiInheritance#//Node")]
    [DebuggerDisplayAttribute("Node {Name}")]
    public partial class Node : ModelElement, INode, IModelElement
    {
        
        /// <summary>
        /// The backing field for the Name property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private string _name;
        
        private static Lazy<ITypedElement> _nameAttribute = new Lazy<ITypedElement>(RetrieveNameAttribute);
        
        private static IClass _classInstance;
        
        /// <summary>
        /// The name property
        /// </summary>
        [DisplayNameAttribute("name")]
        [CategoryAttribute("Node")]
        [XmlElementNameAttribute("name")]
        [IdAttribute()]
        [XmlAttributeAttribute(true)]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                if ((this._name != value))
                {
                    string old = this._name;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnPropertyChanging("Name", e, _nameAttribute);
                    this._name = value;
                    this.OnPropertyChanged("Name", e, _nameAttribute);
                    OnKeyChanged(e);
                }
            }
        }
        
        /// <summary>
        /// Gets the Class model for this type
        /// </summary>
        public new static IClass ClassInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://example.com/multiInheritance#//Node")));
                }
                return _classInstance;
            }
        }
        
        /// <summary>
        /// Gets a value indicating whether the current model element can be identified by an attribute value
        /// </summary>
        public override bool IsIdentified
        {
            get
            {
                return true;
            }
        }
        
        private static ITypedElement RetrieveNameAttribute()
        {
            return ((ITypedElement)(((ModelElement)(TemporaryGeneratedCode.MultiInheritance.Node.ClassInstance)).Resolve("name")));
        }
        
        /// <summary>
        /// Resolves the given attribute name
        /// </summary>
        /// <returns>The attribute value or null if it could not be found</returns>
        /// <param name="attribute">The requested attribute name</param>
        /// <param name="index">The index of this attribute</param>
        protected override object GetAttributeValue(string attribute, int index)
        {
            if ((attribute == "NAME"))
            {
                return this.Name;
            }
            return base.GetAttributeValue(attribute, index);
        }
        
        /// <summary>
        /// Sets a value to the given feature
        /// </summary>
        /// <param name="feature">The requested feature</param>
        /// <param name="value">The value that should be set to that feature</param>
        protected override void SetFeature(string feature, object value)
        {
            if ((feature == "NAME"))
            {
                this.Name = ((string)(value));
                return;
            }
            base.SetFeature(feature, value);
        }
        
        /// <summary>
        /// Gets the property expression for the given attribute
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="attribute">The requested attribute in upper case</param>
        protected override NMF.Expressions.INotifyExpression<object> GetExpressionForAttribute(string attribute)
        {
            if ((attribute == "NAME"))
            {
                return new NodeNameProxy(this);
            }
            return base.GetExpressionForAttribute(attribute);
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override IClass GetClass()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://example.com/multiInheritance#//Node")));
            }
            return _classInstance;
        }
        
        /// <summary>
        /// Gets the identifier string for this model element
        /// </summary>
        /// <returns>The identifier string</returns>
        public override string ToIdentifierString()
        {
            if ((this.Name == null))
            {
                return null;
            }
            return this.Name.ToString();
        }
        
        /// <summary>
        /// Creates the uri with the given fragment starting from the current model element
        /// </summary>
        protected override Uri CreateUriWithFragment(string fragment, bool absolute, IModelElement baseElement)
        {
            return this.CreateUriFromGlobalIdentifier(fragment, absolute);
        }
        
        /// <summary>
        /// Propagates through the composition hierarchy that an entire subtree has been added to a new model
        /// </summary>
        protected override void PropagateNewModel(Model newModel, Model oldModel, IModelElement subtreeRoot)
        {
            string id = this.ToIdentifierString();
            if ((oldModel != null))
            {
                oldModel.UnregisterId(id);
            }
            if ((newModel != null))
            {
                newModel.RegisterId(id, this);
            }
            base.PropagateNewModel(newModel, oldModel, subtreeRoot);
        }
        
        /// <summary>
        /// Notifies clients that the identifier changed
        /// </summary>
        protected override void OnKeyChanged(ValueChangedEventArgs e)
        {
            UpdateRegisteredIdentifier(e);
            base.OnKeyChanged(e);
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the name property
        /// </summary>
        protected sealed class NodeNameProxy : ModelPropertyChange<INode, string>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public NodeNameProxy(INode modelElement) : 
                    base(modelElement, "Name")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override string Value
            {
                get
                {
                    return this.ModelElement.Name;
                }
                set
                {
                    this.ModelElement.Name = value;
                }
            }
        }
    }
    
    /// <summary>
    /// The default implementation of the Named class
    /// </summary>
    [XmlNamespaceAttribute("http://example.com/multiInheritance")]
    [XmlNamespacePrefixAttribute("multiInheritance")]
    [ModelRepresentationClassAttribute("http://example.com/multiInheritance#//Named")]
    public abstract partial class Named : ModelElement, INamed, IModelElement
    {
        
        /// <summary>
        /// The backing field for the Label property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private string _label;
        
        private static Lazy<ITypedElement> _labelAttribute = new Lazy<ITypedElement>(RetrieveLabelAttribute);
        
        private static IClass _classInstance;
        
        /// <summary>
        /// The label property
        /// </summary>
        [DisplayNameAttribute("label")]
        [CategoryAttribute("Named")]
        [XmlElementNameAttribute("label")]
        [XmlAttributeAttribute(true)]
        public string Label
        {
            get
            {
                return this._label;
            }
            set
            {
                if ((this._label != value))
                {
                    string old = this._label;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnPropertyChanging("Label", e, _labelAttribute);
                    this._label = value;
                    this.OnPropertyChanged("Label", e, _labelAttribute);
                }
            }
        }
        
        /// <summary>
        /// Gets the Class model for this type
        /// </summary>
        public new static IClass ClassInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://example.com/multiInheritance#//Named")));
                }
                return _classInstance;
            }
        }
        
        private static ITypedElement RetrieveLabelAttribute()
        {
            return ((ITypedElement)(((ModelElement)(TemporaryGeneratedCode.MultiInheritance.Named.ClassInstance)).Resolve("label")));
        }
        
        /// <summary>
        /// Resolves the given attribute name
        /// </summary>
        /// <returns>The attribute value or null if it could not be found</returns>
        /// <param name="attribute">The requested attribute name</param>
        /// <param name="index">The index of this attribute</param>
        protected override object GetAttributeValue(string attribute, int index)
        {
            if ((attribute == "LABEL"))
            {
                return this.Label;
            }
            return base.GetAttributeValue(attribute, index);
        }
        
        /// <summary>
        /// Sets a value to the given feature
        /// </summary>
        /// <param name="feature">The requested feature</param>
        /// <param name="value">The value that should be set to that feature</param>
        protected override void SetFeature(string feature, object value)
        {
            if ((feature == "LABEL"))
            {
                this.Label = ((string)(value));
                return;
            }
            base.SetFeature(feature, value);
        }
        
        /// <summary>
        /// Gets the property expression for the given attribute
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="attribute">The requested attribute in upper case</param>
        protected override NMF.Expressions.INotifyExpression<object> GetExpressionForAttribute(string attribute)
        {
            if ((attribute == "LABEL"))
            {
                return new NamedLabelProxy(this);
            }
            return base.GetExpressionForAttribute(attribute);
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override IClass GetClass()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://example.com/multiInheritance#//Named")));
            }
            return _classInstance;
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the label property
        /// </summary>
        protected sealed class NamedLabelProxy : ModelPropertyChange<INamed, string>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public NamedLabelProxy(INamed modelElement) : 
                    base(modelElement, "Label")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override string Value
            {
                get
                {
                    return this.ModelElement.Label;
                }
                set
                {
                    this.ModelElement.Label = value;
                }
            }
        }
    }
    
    /// <summary>
    /// The default implementation of the Tagged class
    /// </summary>
    [XmlNamespaceAttribute("http://example.com/multiInheritance")]
    [XmlNamespacePrefixAttribute("multiInheritance")]
    [ModelRepresentationClassAttribute("http://example.com/multiInheritance#//Tagged")]
    public abstract partial class Tagged : ModelElement, ITagged, IModelElement
    {
        
        private static Lazy<ITypedElement> _tagsReference = new Lazy<ITypedElement>(RetrieveTagsReference);
        
        /// <summary>
        /// The backing field for the Tags property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private ObservableCompositionOrderedSet<INode> _tags;
        
        private static IClass _classInstance;
        
        /// <summary>
        /// Creates a new instance
        /// </summary>
        public Tagged()
        {
            this._tags = new ObservableCompositionOrderedSet<INode>(this);
            this._tags.CollectionChanging += this.TagsCollectionChanging;
            this._tags.CollectionChanged += this.TagsCollectionChanged;
        }
        
        /// <summary>
        /// The tags property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("tags")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [ConstantAttribute()]
        public IOrderedSetExpression<INode> Tags
        {
            get
            {
                return this._tags;
            }
        }
        
        /// <summary>
        /// Gets the child model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> Children
        {
            get
            {
                return base.Children.Concat(new TaggedChildrenCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the referenced model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> ReferencedElements
        {
            get
            {
                return base.ReferencedElements.Concat(new TaggedReferencedElementsCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the Class model for this type
        /// </summary>
        public new static IClass ClassInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://example.com/multiInheritance#//Tagged")));
                }
                return _classInstance;
            }
        }
        
        private static ITypedElement RetrieveTagsReference()
        {
            return ((ITypedElement)(((ModelElement)(TemporaryGeneratedCode.MultiInheritance.Tagged.ClassInstance)).Resolve("tags")));
        }
        
        /// <summary>
        /// Forwards CollectionChanging notifications for the Tags property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void TagsCollectionChanging(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanging("Tags", e, _tagsReference);
        }
        
        /// <summary>
        /// Forwards CollectionChanged notifications for the Tags property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void TagsCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanged("Tags", e, _tagsReference);
        }
        
        /// <summary>
        /// Gets the relative URI fragment for the given child model element
        /// </summary>
        /// <returns>A fragment of the relative URI</returns>
        /// <param name="element">The element that should be looked for</param>
        protected override string GetRelativePathForNonIdentifiedChild(IModelElement element)
        {
            int tagsIndex = ModelHelper.IndexOfReference(this.Tags, element);
            if ((tagsIndex != -1))
            {
                return ModelHelper.CreatePath("tags", tagsIndex);
            }
            return base.GetRelativePathForNonIdentifiedChild(element);
        }
        
        /// <summary>
        /// Resolves the given URI to a child model element
        /// </summary>
        /// <returns>The model element or null if it could not be found</returns>
        /// <param name="reference">The requested reference name</param>
        /// <param name="index">The index of this reference</param>
        protected override IModelElement GetModelElementForReference(string reference, int index)
        {
            if ((reference == "TAGS"))
            {
                if ((index < this.Tags.Count))
                {
                    return this.Tags[index];
                }
                else
                {
                    return null;
                }
            }
            return base.GetModelElementForReference(reference, index);
        }
        
        /// <summary>
        /// Gets the Model element collection for the given feature
        /// </summary>
        /// <returns>A non-generic list of elements</returns>
        /// <param name="feature">The requested feature</param>
        protected override System.Collections.IList GetCollectionForFeature(string feature)
        {
            if ((feature == "TAGS"))
            {
                return ((System.Collections.IList)(this.Tags));
            }
            return base.GetCollectionForFeature(feature);
        }
        
        /// <summary>
        /// Gets the property name for the given container
        /// </summary>
        /// <returns>The name of the respective container reference</returns>
        /// <param name="container">The container object</param>
        protected override string GetCompositionName(object container)
        {
            if ((container == this.Tags))
            {
                return "tags";
            }
            return base.GetCompositionName(container);
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override IClass GetClass()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://example.com/multiInheritance#//Tagged")));
            }
            return _classInstance;
        }
        
        /// <summary>
        /// The collection class to to represent the children of the Tagged class
        /// </summary>
        public class TaggedChildrenCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private Tagged _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public TaggedChildrenCollection(Tagged parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    count = (count + this._parent.Tags.Count);
                    return count;
                }
            }
            
            /// <summary>
            /// Creates dependencies for the given collection
            /// </summary>
            /// <returns>A collection of dependencies</returns>
            protected override INotifiable[] CreateDependencies()
            {
                return new INotifiable[] {
                        this._parent.Tags.AsNotifiable()};
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                INode tagsCasted = item.As<INode>();
                if ((tagsCasted != null))
                {
                    this._parent.Tags.Add(tagsCasted);
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.Tags.Clear();
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if (this._parent.Tags.Contains(item))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                IEnumerator<IModelElement> tagsEnumerator = this._parent.Tags.GetEnumerator();
                try
                {
                    for (
                    ; tagsEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = tagsEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    tagsEnumerator.Dispose();
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                INode nodeItem = item.As<INode>();
                if (((nodeItem != null) 
                            && this._parent.Tags.Remove(nodeItem)))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.Tags).GetEnumerator();
            }
        }
        
        /// <summary>
        /// The collection class to to represent the children of the Tagged class
        /// </summary>
        public class TaggedReferencedElementsCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private Tagged _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public TaggedReferencedElementsCollection(Tagged parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    count = (count + this._parent.Tags.Count);
                    return count;
                }
            }
            
            /// <summary>
            /// Creates dependencies for the given collection
            /// </summary>
            /// <returns>A collection of dependencies</returns>
            protected override INotifiable[] CreateDependencies()
            {
                return new INotifiable[] {
                        this._parent.Tags.AsNotifiable()};
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                INode tagsCasted = item.As<INode>();
                if ((tagsCasted != null))
                {
                    this._parent.Tags.Add(tagsCasted);
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.Tags.Clear();
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if (this._parent.Tags.Contains(item))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                IEnumerator<IModelElement> tagsEnumerator = this._parent.Tags.GetEnumerator();
                try
                {
                    for (
                    ; tagsEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = tagsEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    tagsEnumerator.Dispose();
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                INode nodeItem = item.As<INode>();
                if (((nodeItem != null) 
                            && this._parent.Tags.Remove(nodeItem)))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.Tags).GetEnumerator();
            }
        }
    }
    
    /// <summary>
    /// The default implementation of the Item class
    /// </summary>
    [XmlNamespaceAttribute("http://example.com/multiInheritance")]
    [XmlNamespacePrefixAttribute("multiInheritance")]
    [ModelRepresentationClassAttribute("http://example.com/multiInheritance#//Item")]
    public partial class Item : Named, IItem, IModelElement
    {
        
        private static Lazy<ITypedElement> _tagsReference = new Lazy<ITypedElement>(RetrieveTagsReference);
        
        /// <summary>
        /// The backing field for the Tags property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private ObservableCompositionOrderedSet<INode> _tags;
        
        private static IClass _classInstance;
        
        /// <summary>
        /// Creates a new instance
        /// </summary>
        public Item()
        {
            this._tags = new ObservableCompositionOrderedSet<INode>(this);
            this._tags.CollectionChanging += this.TagsCollectionChanging;
            this._tags.CollectionChanged += this.TagsCollectionChanged;
        }
        
        /// <summary>
        /// The tags property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("tags")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [ConstantAttribute()]
        public IOrderedSetExpression<INode> Tags
        {
            get
            {
                return this._tags;
            }
        }
        
        /// <summary>
        /// Gets the child model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> Children
        {
            get
            {
                return base.Children.Concat(new ItemChildrenCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the Class model for this type
        /// </summary>
        public new static IClass ClassInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://example.com/multiInheritance#//Item")));
                }
                return _classInstance;
            }
        }
        
        private static ITypedElement RetrieveTagsReference()
        {
            return ((ITypedElement)(((ModelElement)(TemporaryGeneratedCode.MultiInheritance.Tagged.ClassInstance)).Resolve("tags")));
        }
        
        /// <summary>
        /// Forwards CollectionChanging notifications for the Tags property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void TagsCollectionChanging(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanging("Tags", e, _tagsReference);
        }
        
        /// <summary>
        /// Forwards CollectionChanged notifications for the Tags property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void TagsCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanged("Tags", e, _tagsReference);
        }
        
        /// <summary>
        /// Gets the relative URI fragment for the given child model element
        /// </summary>
        /// <returns>A fragment of the relative URI</returns>
        /// <param name="element">The element that should be looked for</param>
        protected override string GetRelativePathForNonIdentifiedChild(IModelElement element)
        {
            int tagsIndex = ModelHelper.IndexOfReference(this.Tags, element);
            if ((tagsIndex != -1))
            {
                return ModelHelper.CreatePath("tags", tagsIndex);
            }
            return base.GetRelativePathForNonIdentifiedChild(element);
        }
        
        /// <summary>
        /// Resolves the given URI to a child model element
        /// </summary>
        /// <returns>The model element or null if it could not be found</returns>
        /// <param name="reference">The requested reference name</param>
        /// <param name="index">The index of this reference</param>
        protected override IModelElement GetModelElementForReference(string reference, int index)
        {
            if ((reference == "TAGS"))
            {
                if ((index < this.Tags.Count))
                {
                    return this.Tags[index];
                }
                else
                {
                    return null;
                }
            }
            return base.GetModelElementForReference(reference, index);
        }
        
        /// <summary>
        /// Gets the Model element collection for the given feature
        /// </summary>
        /// <returns>A non-generic list of elements</returns>
        /// <param name="feature">The requested feature</param>
        protected override System.Collections.IList GetCollectionForFeature(string feature)
        {
            if ((feature == "TAGS"))
            {
                return ((System.Collections.IList)(this.Tags));
            }
            return base.GetCollectionForFeature(feature);
        }
        
        /// <summary>
        /// Gets the property name for the given container
        /// </summary>
        /// <returns>The name of the respective container reference</returns>
        /// <param name="container">The container object</param>
        protected override string GetCompositionName(object container)
        {
            if ((container == this.Tags))
            {
                return "tags";
            }
            return base.GetCompositionName(container);
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override IClass GetClass()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://example.com/multiInheritance#//Item")));
            }
            return _classInstance;
        }
        
        /// <summary>
        /// The collection class to to represent the children of the Item class
        /// </summary>
        public class ItemChildrenCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private Item _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public ItemChildrenCollection(Item parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    count = (count + this._parent.Tags.Count);
                    return count;
                }
            }
            
            /// <summary>
            /// Creates dependencies for the given collection
            /// </summary>
            /// <returns>A collection of dependencies</returns>
            protected override INotifiable[] CreateDependencies()
            {
                return new INotifiable[] {
                        this._parent.Tags.AsNotifiable()};
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                INode tagsCasted = item.As<INode>();
                if ((tagsCasted != null))
                {
                    this._parent.Tags.Add(tagsCasted);
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.Tags.Clear();
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if (this._parent.Tags.Contains(item))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                IEnumerator<IModelElement> tagsEnumerator = this._parent.Tags.GetEnumerator();
                try
                {
                    for (
                    ; tagsEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = tagsEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    tagsEnumerator.Dispose();
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                INode nodeItem = item.As<INode>();
                if (((nodeItem != null) 
                            && this._parent.Tags.Remove(nodeItem)))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.Tags).GetEnumerator();
            }
        }
    }
    
    /// <summary>
    /// The default implementation of the SpecialItem class
    /// </summary>
    [XmlNamespaceAttribute("http://example.com/multiInheritance")]
    [XmlNamespacePrefixAttribute("multiInheritance")]
    [ModelRepresentationClassAttribute("http://example.com/multiInheritance#//SpecialItem")]
    public partial class SpecialItem : Item, ISpecialItem, IModelElement
    {
        
        private static Lazy<ITypedElement> _extraReference = new Lazy<ITypedElement>(RetrieveExtraReference);
        
        /// <summary>
        /// The backing field for the Extra property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private ObservableCompositionOrderedSet<INode> _extra;
        
        private static IClass _classInstance;
        
        /// <summary>
        /// Creates a new instance
        /// </summary>
        public SpecialItem()
        {
            this._extra = new ObservableCompositionOrderedSet<INode>(this);
            this._extra.CollectionChanging += this.ExtraCollectionChanging;
            this._extra.CollectionChanged += this.ExtraCollectionChanged;
        }
        
        /// <summary>
        /// The extra property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("extra")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [ConstantAttribute()]
        public IOrderedSetExpression<INode> Extra
        {
            get
            {
                return this._extra;
            }
        }
        
        /// <summary>
        /// Gets the child model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> Children
        {
            get
            {
                return base.Children.Concat(new SpecialItemChildrenCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the referenced model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> ReferencedElements
        {
            get
            {
                return base.ReferencedElements.Concat(new SpecialItemReferencedElementsCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the Class model for this type
        /// </summary>
        public new static IClass ClassInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://example.com/multiInheritance#//SpecialItem")));
                }
                return _classInstance;
            }
        }
        
        private static ITypedElement RetrieveExtraReference()
        {
            return ((ITypedElement)(((ModelElement)(TemporaryGeneratedCode.MultiInheritance.SpecialItem.ClassInstance)).Resolve("extra")));
        }
        
        /// <summary>
        /// Forwards CollectionChanging notifications for the Extra property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void ExtraCollectionChanging(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanging("Extra", e, _extraReference);
        }
        
        /// <summary>
        /// Forwards CollectionChanged notifications for the Extra property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void ExtraCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanged("Extra", e, _extraReference);
        }
        
        /// <summary>
        /// Gets the relative URI fragment for the given child model element
        /// </summary>
        /// <returns>A fragment of the relative URI</returns>
        /// <param name="element">The element that should be looked for</param>
        protected override string GetRelativePathForNonIdentifiedChild(IModelElement element)
        {
            int extraIndex = ModelHelper.IndexOfReference(this.Extra, element);
            if ((extraIndex != -1))
            {
                return ModelHelper.CreatePath("extra", extraIndex);
            }
            return base.GetRelativePathForNonIdentifiedChild(element);
        }
        
        /// <summary>
        /// Resolves the given URI to a child model element
        /// </summary>
        /// <returns>The model element or null if it could not be found</returns>
        /// <param name="reference">The requested reference name</param>
        /// <param name="index">The index of this reference</param>
        protected override IModelElement GetModelElementForReference(string reference, int index)
        {
            if ((reference == "EXTRA"))
            {
                if ((index < this.Extra.Count))
                {
                    return this.Extra[index];
                }
                else
                {
                    return null;
                }
            }
            return base.GetModelElementForReference(reference, index);
        }
        
        /// <summary>
        /// Gets the Model element collection for the given feature
        /// </summary>
        /// <returns>A non-generic list of elements</returns>
        /// <param name="feature">The requested feature</param>
        protected override System.Collections.IList GetCollectionForFeature(string feature)
        {
            if ((feature == "EXTRA"))
            {
                return ((System.Collections.IList)(this.Extra));
            }
            return base.GetCollectionForFeature(feature);
        }
        
        /// <summary>
        /// Gets the property name for the given container
        /// </summary>
        /// <returns>The name of the respective container reference</returns>
        /// <param name="container">The container object</param>
        protected override string GetCompositionName(object container)
        {
            if ((container == this.Extra))
            {
                return "extra";
            }
            return base.GetCompositionName(container);
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override IClass GetClass()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://example.com/multiInheritance#//SpecialItem")));
            }
            return _classInstance;
        }
        
        /// <summary>
        /// The collection class to to represent the children of the SpecialItem class
        /// </summary>
        public class SpecialItemChildrenCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private SpecialItem _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public SpecialItemChildrenCollection(SpecialItem parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    count = (count + this._parent.Extra.Count);
                    return count;
                }
            }
            
            /// <summary>
            /// Creates dependencies for the given collection
            /// </summary>
            /// <returns>A collection of dependencies</returns>
            protected override INotifiable[] CreateDependencies()
            {
                return new INotifiable[] {
                        this._parent.Extra.AsNotifiable()};
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                INode extraCasted = item.As<INode>();
                if ((extraCasted != null))
                {
                    this._parent.Extra.Add(extraCasted);
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.Extra.Clear();
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if (this._parent.Extra.Contains(item))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                IEnumerator<IModelElement> extraEnumerator = this._parent.Extra.GetEnumerator();
                try
                {
                    for (
                    ; extraEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = extraEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    extraEnumerator.Dispose();
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                INode nodeItem = item.As<INode>();
                if (((nodeItem != null) 
                            && this._parent.Extra.Remove(nodeItem)))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.Extra).GetEnumerator();
            }
        }
        
        /// <summary>
        /// The collection class to to represent the children of the SpecialItem class
        /// </summary>
        public class SpecialItemReferencedElementsCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private SpecialItem _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public SpecialItemReferencedElementsCollection(SpecialItem parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    count = (count + this._parent.Extra.Count);
                    return count;
                }
            }
            
            /// <summary>
            /// Creates dependencies for the given collection
            /// </summary>
            /// <returns>A collection of dependencies</returns>
            protected override INotifiable[] CreateDependencies()
            {
                return new INotifiable[] {
                        this._parent.Extra.AsNotifiable()};
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                INode extraCasted = item.As<INode>();
                if ((extraCasted != null))
                {
                    this._parent.Extra.Add(extraCasted);
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.Extra.Clear();
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if (this._parent.Extra.Contains(item))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                IEnumerator<IModelElement> extraEnumerator = this._parent.Extra.GetEnumerator();
                try
                {
                    for (
                    ; extraEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = extraEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    extraEnumerator.Dispose();
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                INode nodeItem = item.As<INode>();
                if (((nodeItem != null) 
                            && this._parent.Extra.Remove(nodeItem)))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.Extra).GetEnumerator();
            }
        }
    }
    
    /// <summary>
    /// The public interface for SpecialItem
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(SpecialItem))]
    [XmlDefaultImplementationTypeAttribute(typeof(SpecialItem))]
    [ModelRepresentationClassAttribute("http://example.com/multiInheritance#//SpecialItem")]
    public partial interface ISpecialItem : IModelElement, IItem
    {
        
        /// <summary>
        /// The extra property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("extra")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [ConstantAttribute()]
        IOrderedSetExpression<INode> Extra
        {
            get;
        }
    }
    
    /// <summary>
    /// The public interface for Item
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(Item))]
    [XmlDefaultImplementationTypeAttribute(typeof(Item))]
    [ModelRepresentationClassAttribute("http://example.com/multiInheritance#//Item")]
    public partial interface IItem : IModelElement, ITagged, INamed
    {
    }
    
    /// <summary>
    /// The public interface for Tagged
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(Tagged))]
    [XmlDefaultImplementationTypeAttribute(typeof(Tagged))]
    [ModelRepresentationClassAttribute("http://example.com/multiInheritance#//Tagged")]
    public partial interface ITagged : IModelElement
    {
        
        /// <summary>
        /// The tags property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("tags")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [ConstantAttribute()]
        IOrderedSetExpression<INode> Tags
        {
            get;
        }
    }
    
    /// <summary>
    /// The public interface for Named
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(Named))]
    [XmlDefaultImplementationTypeAttribute(typeof(Named))]
    [ModelRepresentationClassAttribute("http://example.com/multiInheritance#//Named")]
    public partial interface INamed : IModelElement
    {
        
        /// <summary>
        /// The label property
        /// </summary>
        [DisplayNameAttribute("label")]
        [CategoryAttribute("Named")]
        [XmlElementNameAttribute("label")]
        [XmlAttributeAttribute(true)]
        string Label
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// The public interface for Node
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(Node))]
    [XmlDefaultImplementationTypeAttribute(typeof(Node))]
    [ModelRepresentationClassAttribute("http://example.com/multiInheritance#//Node")]
    public partial interface INode : IModelElement
    {
        
        /// <summary>
        /// The name property
        /// </summary>
        [DisplayNameAttribute("name")]
        [CategoryAttribute("Node")]
        [XmlElementNameAttribute("name")]
        [IdAttribute()]
        [XmlAttributeAttribute(true)]
        string Name
        {
            get;
            set;
        }
    }
}
