//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemporaryGeneratedCode.Refines
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Linq;
    using NMF.Expressions;
    using NMF.Expressions.Linq;
    using NMF.Models;
    using NMF.Models.Meta;
    using NMF.Models.Collections;
    using NMF.Models.Expressions;
    using NMF.Collections.Generic;
    using NMF.Collections.ObjectModel;
    using NMF.Serialization;
    using NMF.Utilities;
    using NMF.Models.Repository;
    using System.Collections.Specialized;
    
    
    /// <summary>
    /// The default implementation of the Node class
    /// </summary>
    [XmlIdentifierAttribute("name")]
    [XmlNamespaceAttribute("http://example.com/refines")]
    [XmlNamespacePrefixAttribute("refines")]
    [ModelRepresentationClassAttribute("http://example.com/refines#//Node")]
    [DebuggerDisplayAttribute("Node {Name}")]
    public partial class Node : ModelElement, INode, IModelElement
    {
        
        /// <summary>
        /// The backing field for the Name property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private string _name;
        
        private static Lazy<ITypedElement> _nameAttribute = new Lazy<ITypedElement>(RetrieveNameAttribute);
        
        private static IClass _classInstance;
        
        /// <summary>
        /// The name property
        /// </summary>
        [DisplayNameAttribute("name")]
        [CategoryAttribute("Node")]
        [XmlElementNameAttribute("name")]
        [IdAttribute()]
        [XmlAttributeAttribute(true)]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                if ((this._name != value))
                {
                    string old = this._name;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnPropertyChanging("Name", e, _nameAttribute);
                    this._name = value;
                    this.OnPropertyChanged("Name", e, _nameAttribute);
                    OnKeyChanged(e);
                }
            }
        }
        
        /// <summary>
        /// Gets the Class model for this type
        /// </summary>
        public new static IClass ClassInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://example.com/refines#//Node")));
                }
                return _classInstance;
            }
        }
        
        /// <summary>
        /// Gets a value indicating whether the current model element can be identified by an attribute value
        /// </summary>
        public override bool IsIdentified
        {
            get
            {
                return true;
            }
        }
        
        private static ITypedElement RetrieveNameAttribute()
        {
            return ((ITypedElement)(((ModelElement)(TemporaryGeneratedCode.Refines.Node.ClassInstance)).Resolve("name")));
        }
        
        /// <summary>
        /// Resolves the given attribute name
        /// </summary>
        /// <returns>The attribute value or null if it could not be found</returns>
        /// <param name="attribute">The requested attribute name</param>
        /// <param name="index">The index of this attribute</param>
        protected override object GetAttributeValue(string attribute, int index)
        {
            if ((attribute == "NAME"))
            {
                return this.Name;
            }
            return base.GetAttributeValue(attribute, index);
        }
        
        /// <summary>
        /// Sets a value to the given feature
        /// </summary>
        /// <param name="feature">The requested feature</param>
        /// <param name="value">The value that should be set to that feature</param>
        protected override void SetFeature(string feature, object value)
        {
            if ((feature == "NAME"))
            {
                this.Name = ((string)(value));
                return;
            }
            base.SetFeature(feature, value);
        }
        
        /// <summary>
        /// Gets the property expression for the given attribute
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="attribute">The requested attribute in upper case</param>
        protected override NMF.Expressions.INotifyExpression<object> GetExpressionForAttribute(string attribute)
        {
            if ((attribute == "NAME"))
            {
                return new NodeNameProxy(this);
            }
            return base.GetExpressionForAttribute(attribute);
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override IClass GetClass()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://example.com/refines#//Node")));
            }
            return _classInstance;
        }
        
        /// <summary>
        /// Gets the identifier string for this model element
        /// </summary>
        /// <returns>The identifier string</returns>
        public override string ToIdentifierString()
        {
            if ((this.Name == null))
            {
                return null;
            }
            return this.Name.ToString();
        }
        
        /// <summary>
        /// Creates the uri with the given fragment starting from the current model element
        /// </summary>
        protected override Uri CreateUriWithFragment(string fragment, bool absolute, IModelElement baseElement)
        {
            return this.CreateUriFromGlobalIdentifier(fragment, absolute);
        }
        
        /// <summary>
        /// Propagates through the composition hierarchy that an entire subtree has been added to a new model
        /// </summary>
        protected override void PropagateNewModel(Model newModel, Model oldModel, IModelElement subtreeRoot)
        {
            string id = this.ToIdentifierString();
            if ((oldModel != null))
            {
                oldModel.UnregisterId(id);
            }
            if ((newModel != null))
            {
                newModel.RegisterId(id, this);
            }
            base.PropagateNewModel(newModel, oldModel, subtreeRoot);
        }
        
        /// <summary>
        /// Notifies clients that the identifier changed
        /// </summary>
        protected override void OnKeyChanged(ValueChangedEventArgs e)
        {
            UpdateRegisteredIdentifier(e);
            base.OnKeyChanged(e);
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the name property
        /// </summary>
        protected sealed class NodeNameProxy : ModelPropertyChange<INode, string>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public NodeNameProxy(INode modelElement) : 
                    base(modelElement, "Name")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override string Value
            {
                get
                {
                    return this.ModelElement.Name;
                }
                set
                {
                    this.ModelElement.Name = value;
                }
            }
        }
    }
    
    /// <summary>
    /// The default implementation of the Base class
    /// </summary>
    [XmlNamespaceAttribute("http://example.com/refines")]
    [XmlNamespacePrefixAttribute("refines")]
    [ModelRepresentationClassAttribute("http://example.com/refines#//Base")]
    public abstract partial class Base : ModelElement, IBase, IModelElement
    {
        
        private static Lazy<ITypedElement> _itemReference = new Lazy<ITypedElement>(RetrieveItemReference);
        
        /// <summary>
        /// The backing field for the Item property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private INode _item;
        
        private static Lazy<ITypedElement> _childrenReference = new Lazy<ITypedElement>(RetrieveChildrenReference);
        
        /// <summary>
        /// The backing field for the Children_ property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private ObservableCompositionList<INode> _children_;
        
        private static IClass _classInstance;
        
        /// <summary>
        /// Creates a new instance
        /// </summary>
        public Base()
        {
            this._children_ = new ObservableCompositionList<INode>(this);
            this._children_.CollectionChanging += this.Children_CollectionChanging;
            this._children_.CollectionChanged += this.Children_CollectionChanged;
        }
        
        /// <summary>
        /// The item property
        /// </summary>
        [DisplayNameAttribute("item")]
        [CategoryAttribute("Base")]
        [XmlElementNameAttribute("item")]
        [XmlAttributeAttribute(true)]
        public INode Item
        {
            get
            {
                return this._item;
            }
            set
            {
                if ((this._item != value))
                {
                    INode old = this._item;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnPropertyChanging("Item", e, _itemReference);
                    this._item = value;
                    if ((old != null))
                    {
                        old.Deleted -= this.OnResetItem;
                    }
                    if ((value != null))
                    {
                        value.Deleted += this.OnResetItem;
                    }
                    this.OnPropertyChanged("Item", e, _itemReference);
                }
            }
        }
        
        /// <summary>
        /// The children property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("children")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [ConstantAttribute()]
        public IListExpression<INode> Children_
        {
            get
            {
                return this._children_;
            }
        }
        
        /// <summary>
        /// Gets the child model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> Children
        {
            get
            {
                return base.Children.Concat(new BaseChildrenCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the referenced model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> ReferencedElements
        {
            get
            {
                return base.ReferencedElements.Concat(new BaseReferencedElementsCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the Class model for this type
        /// </summary>
        public new static IClass ClassInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://example.com/refines#//Base")));
                }
                return _classInstance;
            }
        }
        
        private static ITypedElement RetrieveItemReference()
        {
            return ((ITypedElement)(((ModelElement)(TemporaryGeneratedCode.Refines.Base.ClassInstance)).Resolve("item")));
        }
        
        /// <summary>
        /// Handles the event that the Item property must reset
        /// </summary>
        /// <param name="sender">The object that sent this reset request</param>
        /// <param name="eventArgs">The event data for the reset event</param>
        private void OnResetItem(object sender, EventArgs eventArgs)
        {
            if ((sender == this.Item))
            {
                this.Item = null;
            }
        }
        
        private static ITypedElement RetrieveChildrenReference()
        {
            return ((ITypedElement)(((ModelElement)(TemporaryGeneratedCode.Refines.Base.ClassInstance)).Resolve("children")));
        }
        
        /// <summary>
        /// Forwards CollectionChanging notifications for the Children_ property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void Children_CollectionChanging(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanging("Children_", e, _childrenReference);
        }
        
        /// <summary>
        /// Forwards CollectionChanged notifications for the Children_ property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void Children_CollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanged("Children_", e, _childrenReference);
        }
        
        /// <summary>
        /// Gets the relative URI fragment for the given child model element
        /// </summary>
        /// <returns>A fragment of the relative URI</returns>
        /// <param name="element">The element that should be looked for</param>
        protected override string GetRelativePathForNonIdentifiedChild(IModelElement element)
        {
            int childrenIndex = ModelHelper.IndexOfReference(this.Children_, element);
            if ((childrenIndex != -1))
            {
                return ModelHelper.CreatePath("children", childrenIndex);
            }
            return base.GetRelativePathForNonIdentifiedChild(element);
        }
        
        /// <summary>
        /// Resolves the given URI to a child model element
        /// </summary>
        /// <returns>The model element or null if it could not be found</returns>
        /// <param name="reference">The requested reference name</param>
        /// <param name="index">The index of this reference</param>
        protected override IModelElement GetModelElementForReference(string reference, int index)
        {
            if ((reference == "ITEM"))
            {
                return this.Item;
            }
            if ((reference == "CHILDREN"))
            {
                if ((index < this.Children_.Count))
                {
                    return this.Children_[index];
                }
                else
                {
                    return null;
                }
            }
            return base.GetModelElementForReference(reference, index);
        }
        
        /// <summary>
        /// Gets the Model element collection for the given feature
        /// </summary>
        /// <returns>A non-generic list of elements</returns>
        /// <param name="feature">The requested feature</param>
        protected override System.Collections.IList GetCollectionForFeature(string feature)
        {
            if ((feature == "CHILDREN"))
            {
                return ((System.Collections.IList)(this.Children_));
            }
            return base.GetCollectionForFeature(feature);
        }
        
        /// <summary>
        /// Sets a value to the given feature
        /// </summary>
        /// <param name="feature">The requested feature</param>
        /// <param name="value">The value that should be set to that feature</param>
        protected override void SetFeature(string feature, object value)
        {
            if ((feature == "ITEM"))
            {
                this.Item = ((INode)(value));
                return;
            }
            base.SetFeature(feature, value);
        }
        
        /// <summary>
        /// Gets the property expression for the given reference
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="reference">The requested reference in upper case</param>
        protected override NMF.Expressions.INotifyExpression<NMF.Models.IModelElement> GetExpressionForReference(string reference)
        {
            if ((reference == "ITEM"))
            {
                return new BaseItemProxy(this);
            }
            return base.GetExpressionForReference(reference);
        }
        
        /// <summary>
        /// Gets the property name for the given container
        /// </summary>
        /// <returns>The name of the respective container reference</returns>
        /// <param name="container">The container object</param>
        protected override string GetCompositionName(object container)
        {
            if ((container == this.Children_))
            {
                return "children";
            }
            return base.GetCompositionName(container);
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override IClass GetClass()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://example.com/refines#//Base")));
            }
            return _classInstance;
        }
        
        /// <summary>
        /// The collection class to to represent the children of the Base class
        /// </summary>
        public class BaseChildrenCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private Base _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public BaseChildrenCollection(Base parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    count = (count + this._parent.Children_.Count);
                    return count;
                }
            }
            
            /// <summary>
            /// Creates dependencies for the given collection
            /// </summary>
            /// <returns>A collection of dependencies</returns>
            protected override INotifiable[] CreateDependencies()
            {
                return new INotifiable[] {
                        this._parent.Children_.AsNotifiable()};
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                INode childrenCasted = item.As<INode>();
                if ((childrenCasted != null))
                {
                    this._parent.Children_.Add(childrenCasted);
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.Children_.Clear();
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if (this._parent.Children_.Contains(item))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                IEnumerator<IModelElement> childrenEnumerator = this._parent.Children_.GetEnumerator();
                try
                {
                    for (
                    ; childrenEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = childrenEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    childrenEnumerator.Dispose();
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                INode nodeItem = item.As<INode>();
                if (((nodeItem != null) 
                            && this._parent.Children_.Remove(nodeItem)))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.Children_).GetEnumerator();
            }
        }
        
        /// <summary>
        /// The collection class to to represent the children of the Base class
        /// </summary>
        public class BaseReferencedElementsCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private Base _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public BaseReferencedElementsCollection(Base parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    if ((this._parent.Item != null))
                    {
                        count = (count + 1);
                    }
                    count = (count + this._parent.Children_.Count);
                    return count;
                }
            }
            
            /// <summary>
            /// Creates dependencies for the given collection
            /// </summary>
            /// <returns>A collection of dependencies</returns>
            protected override INotifiable[] CreateDependencies()
            {
                return new INotifiable[] {
                        new BaseItemProxy(this._parent),
                        this._parent.Children_.AsNotifiable()};
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                if ((this._parent.Item == null))
                {
                    INode itemCasted = item.As<INode>();
                    if ((itemCasted != null))
                    {
                        this._parent.Item = itemCasted;
                        return;
                    }
                }
                INode childrenCasted = item.As<INode>();
                if ((childrenCasted != null))
                {
                    this._parent.Children_.Add(childrenCasted);
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.Item = null;
                this._parent.Children_.Clear();
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if ((item == this._parent.Item))
                {
                    return true;
                }
                if (this._parent.Children_.Contains(item))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                if ((this._parent.Item != null))
                {
                    array[arrayIndex] = this._parent.Item;
                    arrayIndex = (arrayIndex + 1);
                }
                IEnumerator<IModelElement> childrenEnumerator = this._parent.Children_.GetEnumerator();
                try
                {
                    for (
                    ; childrenEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = childrenEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    childrenEnumerator.Dispose();
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                if ((this._parent.Item == item))
                {
                    this._parent.Item = null;
                    return true;
                }
                INode nodeItem = item.As<INode>();
                if (((nodeItem != null) 
                            && this._parent.Children_.Remove(nodeItem)))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.Item).Concat(this._parent.Children_).GetEnumerator();
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the item property
        /// </summary>
        protected sealed class BaseItemProxy : ModelPropertyChange<IBase, INode>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public BaseItemProxy(IBase modelElement) : 
                    base(modelElement, "Item")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override INode Value
            {
                get
                {
                    return this.ModelElement.Item;
                }
                set
                {
                    this.ModelElement.Item = value;
                }
            }
        }
    }
    
    /// <summary>
    /// The default implementation of the Concrete class
    /// </summary>
    [XmlNamespaceAttribute("http://example.com/refines")]
    [XmlNamespacePrefixAttribute("refines")]
    [ModelRepresentationClassAttribute("http://example.com/refines#//Concrete")]
    public partial class Concrete : ModelElement, IConcrete, IModelElement
    {
        
        private static Lazy<ITypedElement> _itemReference = new Lazy<ITypedElement>(RetrieveItemReference);
        
        /// <summary>
        /// The backing field for the Item property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private INode _item;
        
        private static Lazy<ITypedElement> _childrenReference = new Lazy<ITypedElement>(RetrieveChildrenReference);
        
        /// <summary>
        /// The backing field for the Children_ property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private ObservableCompositionOrderedSet<INode> _children_;
        
        private static IClass _classInstance;
        
        /// <summary>
        /// Creates a new instance
        /// </summary>
        public Concrete()
        {
            this._children_ = new ObservableCompositionOrderedSet<INode>(this);
            this._children_.CollectionChanging += this.Children_CollectionChanging;
            this._children_.CollectionChanged += this.Children_CollectionChanged;
        }
        
        /// <summary>
        /// The item property
        /// </summary>
        [DisplayNameAttribute("item")]
        [CategoryAttribute("Concrete")]
        [XmlElementNameAttribute("item")]
        [XmlAttributeAttribute(true)]
        public INode Item
        {
            get
            {
                return this._item;
            }
            set
            {
                if ((this._item != value))
                {
                    INode old = this._item;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnPropertyChanging("Item", e, _itemReference);
                    this._item = value;
                    if ((old != null))
                    {
                        old.Deleted -= this.OnResetItem;
                    }
                    if ((value != null))
                    {
                        value.Deleted += this.OnResetItem;
                    }
                    this.OnPropertyChanged("Item", e, _itemReference);
                }
            }
        }
        
        /// <summary>
        /// The children property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("children")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [ConstantAttribute()]
        public IOrderedSetExpression<INode> Children_
        {
            get
            {
                return this._children_;
            }
        }
        
        INode IBase.Item
        {
            get
            {
                IConcrete _this = this;
                return _this.Item;
            }
            set
            {
                IConcrete _this = this;
                _this.Item = value;
            }
        }
        
        IListExpression<INode> IBase.Children_
        {
            get
            {
                return new ConcreteRefinedChildrenCollection(this);
            }
        }
        
        /// <summary>
        /// Gets the child model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> Children
        {
            get
            {
                return base.Children.Concat(new ConcreteChildrenCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the referenced model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> ReferencedElements
        {
            get
            {
                return base.ReferencedElements.Concat(new ConcreteReferencedElementsCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the Class model for this type
        /// </summary>
        public new static IClass ClassInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://example.com/refines#//Concrete")));
                }
                return _classInstance;
            }
        }
        
        private static ITypedElement RetrieveItemReference()
        {
            return ((ITypedElement)(((ModelElement)(TemporaryGeneratedCode.Refines.Concrete.ClassInstance)).Resolve("item")));
        }
        
        /// <summary>
        /// Handles the event that the Item property must reset
        /// </summary>
        /// <param name="sender">The object that sent this reset request</param>
        /// <param name="eventArgs">The event data for the reset event</param>
        private void OnResetItem(object sender, EventArgs eventArgs)
        {
            if ((sender == this.Item))
            {
                this.Item = null;
            }
        }
        
        private static ITypedElement RetrieveChildrenReference()
        {
            return ((ITypedElement)(((ModelElement)(TemporaryGeneratedCode.Refines.Concrete.ClassInstance)).Resolve("children")));
        }
        
        /// <summary>
        /// Forwards CollectionChanging notifications for the Children_ property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void Children_CollectionChanging(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanging("Children_", e, _childrenReference);
        }
        
        /// <summary>
        /// Forwards CollectionChanged notifications for the Children_ property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void Children_CollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanged("Children_", e, _childrenReference);
        }
        
        /// <summary>
        /// Gets the relative URI fragment for the given child model element
        /// </summary>
        /// <returns>A fragment of the relative URI</returns>
        /// <param name="element">The element that should be looked for</param>
        protected override string GetRelativePathForNonIdentifiedChild(IModelElement element)
        {
            int childrenIndex = ModelHelper.IndexOfReference(this.Children_, element);
            if ((childrenIndex != -1))
            {
                return ModelHelper.CreatePath("children", childrenIndex);
            }
            return base.GetRelativePathForNonIdentifiedChild(element);
        }
        
        /// <summary>
        /// Resolves the given URI to a child model element
        /// </summary>
        /// <returns>The model element or null if it could not be found</returns>
        /// <param name="reference">The requested reference name</param>
        /// <param name="index">The index of this reference</param>
        protected override IModelElement GetModelElementForReference(string reference, int index)
        {
            if ((reference == "ITEM"))
            {
                return this.Item;
            }
            if ((reference == "CHILDREN"))
            {
                if ((index < this.Children_.Count))
                {
                    return this.Children_[index];
                }
                else
                {
                    return null;
                }
            }
            return base.GetModelElementForReference(reference, index);
        }
        
        /// <summary>
        /// Gets the Model element collection for the given feature
        /// </summary>
        /// <returns>A non-generic list of elements</returns>
        /// <param name="feature">The requested feature</param>
        protected override System.Collections.IList GetCollectionForFeature(string feature)
        {
            if ((feature == "CHILDREN"))
            {
                return ((System.Collections.IList)(this.Children_));
            }
            return base.GetCollectionForFeature(feature);
        }
        
        /// <summary>
        /// Sets a value to the given feature
        /// </summary>
        /// <param name="feature">The requested feature</param>
        /// <param name="value">The value that should be set to that feature</param>
        protected override void SetFeature(string feature, object value)
        {
            if ((feature == "ITEM"))
            {
                ((IBase)(this)).Item = ((INode)(value));
                return;
            }
            base.SetFeature(feature, value);
        }
        
        /// <summary>
        /// Gets the property expression for the given reference
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="reference">The requested reference in upper case</param>
        protected override NMF.Expressions.INotifyExpression<NMF.Models.IModelElement> GetExpressionForReference(string reference)
        {
            if ((reference == "ITEM"))
            {
                return new ConcreteItemProxy(this);
            }
            return base.GetExpressionForReference(reference);
        }
        
        /// <summary>
        /// Gets the property name for the given container
        /// </summary>
        /// <returns>The name of the respective container reference</returns>
        /// <param name="container">The container object</param>
        protected override string GetCompositionName(object container)
        {
            if ((container == this.Children_))
            {
                return "children";
            }
            return base.GetCompositionName(container);
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override IClass GetClass()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://example.com/refines#//Concrete")));
            }
            return _classInstance;
        }
        
        /// <summary>
        /// The collection class to to represent the children of the Concrete class
        /// </summary>
        public class ConcreteChildrenCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private Concrete _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public ConcreteChildrenCollection(Concrete parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    count = (count + this._parent.Children_.Count);
                    return count;
                }
            }
            
            /// <summary>
            /// Creates dependencies for the given collection
            /// </summary>
            /// <returns>A collection of dependencies</returns>
            protected override INotifiable[] CreateDependencies()
            {
                return new INotifiable[] {
                        this._parent.Children_.AsNotifiable()};
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                INode childrenCasted = item.As<INode>();
                if ((childrenCasted != null))
                {
                    this._parent.Children_.Add(childrenCasted);
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.Children_.Clear();
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if (this._parent.Children_.Contains(item))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                IEnumerator<IModelElement> childrenEnumerator = this._parent.Children_.GetEnumerator();
                try
                {
                    for (
                    ; childrenEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = childrenEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    childrenEnumerator.Dispose();
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                INode nodeItem = item.As<INode>();
                if (((nodeItem != null) 
                            && this._parent.Children_.Remove(nodeItem)))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.Children_).GetEnumerator();
            }
        }
        
        /// <summary>
        /// The collection class to to represent the children of the Concrete class
        /// </summary>
        public class ConcreteReferencedElementsCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private Concrete _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public ConcreteReferencedElementsCollection(Concrete parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    if ((this._parent.Item != null))
                    {
                        count = (count + 1);
                    }
                    count = (count + this._parent.Children_.Count);
                    return count;
                }
            }
            
            /// <summary>
            /// Creates dependencies for the given collection
            /// </summary>
            /// <returns>A collection of dependencies</returns>
            protected override INotifiable[] CreateDependencies()
            {
                return new INotifiable[] {
                        new ConcreteItemProxy(this._parent),
                        this._parent.Children_.AsNotifiable()};
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                if ((this._parent.Item == null))
                {
                    INode itemCasted = item.As<INode>();
                    if ((itemCasted != null))
                    {
                        this._parent.Item = itemCasted;
                        return;
                    }
                }
                INode childrenCasted = item.As<INode>();
                if ((childrenCasted != null))
                {
                    this._parent.Children_.Add(childrenCasted);
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.Item = null;
                this._parent.Children_.Clear();
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if ((item == this._parent.Item))
                {
                    return true;
                }
                if (this._parent.Children_.Contains(item))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                if ((this._parent.Item != null))
                {
                    array[arrayIndex] = this._parent.Item;
                    arrayIndex = (arrayIndex + 1);
                }
                IEnumerator<IModelElement> childrenEnumerator = this._parent.Children_.GetEnumerator();
                try
                {
                    for (
                    ; childrenEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = childrenEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    childrenEnumerator.Dispose();
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                if ((this._parent.Item == item))
                {
                    this._parent.Item = null;
                    return true;
                }
                INode nodeItem = item.As<INode>();
                if (((nodeItem != null) 
                            && this._parent.Children_.Remove(nodeItem)))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.Item).Concat(this._parent.Children_).GetEnumerator();
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the item property
        /// </summary>
        protected sealed class ConcreteItemProxy : ModelPropertyChange<IConcrete, INode>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public ConcreteItemProxy(IConcrete modelElement) : 
                    base(modelElement, "Item")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override INode Value
            {
                get
                {
                    return this.ModelElement.Item;
                }
                set
                {
                    this.ModelElement.Item = value;
                }
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the item property
        /// </summary>
        protected sealed class BaseItemProxy : ModelPropertyChange<IBase, INode>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public BaseItemProxy(IBase modelElement) : 
                    base(modelElement, "Item")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override INode Value
            {
                get
                {
                    return this.ModelElement.Item;
                }
                set
                {
                    this.ModelElement.Item = value;
                }
            }
        }
    }
    
    /// <summary>
    /// The collection class to implement the refined children reference for the Concrete class
    /// </summary>
    public class ConcreteRefinedChildrenCollection : ICollectionExpression<INode>, ICollection<INode>, IListExpression<INode>, IList<INode>
    {
        
        private IConcrete _parent;
        
        /// <summary>
        /// Creates a new instance
        /// </summary>
        public ConcreteRefinedChildrenCollection(IConcrete parent)
        {
            this._parent = parent;
            parent.Children_.AsNotifiable().CollectionChanged += this.HandleCollectionChange;
        }
        
        /// <summary>
        /// Gets the amount of elements contained in this collection
        /// </summary>
        public virtual int Count
        {
            get
            {
                int count = 0;
                count = (count + this._parent.Children_.Count);
                return count;
            }
        }
        
        /// <summary>
        /// Gets a value indicating that the collection is not read-only
        /// </summary>
        public virtual bool IsReadOnly
        {
            get
            {
                return false;
            }
        }
        
        /// <summary>
        /// Gets or sets the item at the given position
        /// </summary>
        public virtual INode this[int index]
        {
            get
            {
                int runningIndex = 0;
                if ((this._parent.Children_.Count 
                            <= (index - runningIndex)))
                {
                    return this._parent.Children_[(index - runningIndex)];
                }
                else
                {
                    runningIndex = (runningIndex + this._parent.Children_.Count);
                }
                throw new System.IndexOutOfRangeException();
            }
            set
            {
                int runningIndex = 0;
                if ((this._parent.Children_.Count 
                            <= (index - runningIndex)))
                {
                    this._parent.Children_[(index - runningIndex)] = value;
                }
                else
                {
                    runningIndex = (runningIndex + this._parent.Children_.Count);
                }
                throw new System.IndexOutOfRangeException();
            }
        }
        
        /// <summary>
        /// Returns that this composed collection is always attached.
        /// </summary>
        public bool IsAttached
        {
            get
            {
                return true;
            }
        }
        
        /// <summary>
        /// Gets fired when the contents of this collection changes
        /// </summary>
        public event NotifyCollectionChangedEventHandler CollectionChanged;
        
        /// <summary>
        /// Fires the CollectionChanged event
        /// </summary>
        protected virtual void OnCollectionChanged(System.Collections.Specialized.NotifyCollectionChangedEventArgs eventArgs)
        {
            System.Collections.Specialized.NotifyCollectionChangedEventHandler handler = this.CollectionChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        private void HandleCollectionChange(object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs eventArgs)
        {
            this.OnCollectionChanged(eventArgs);
        }
        
        /// <summary>
        /// Adds the given element to the collection
        /// </summary>
        /// <param name="item">The item to add</param>
        public virtual void Add(INode item)
        {
            this._parent.Children_.Add(item);
        }
        
        /// <summary>
        /// Clears the collection and resets all references that implement it.
        /// </summary>
        public virtual void Clear()
        {
            this._parent.Children_.Clear();
        }
        
        /// <summary>
        /// Gets a value indicating whether the given element is contained in the collection
        /// </summary>
        /// <returns>True, if it is contained, otherwise False</returns>
        /// <param name="item">The item that should be looked out for</param>
        public virtual bool Contains(INode item)
        {
            if (this._parent.Children_.Contains(item))
            {
                return true;
            }
            return false;
        }
        
        /// <summary>
        /// Copies the contents of the collection to the given array starting from the given array index
        /// </summary>
        /// <param name="array">The array in which the elements should be copied</param>
        /// <param name="arrayIndex">The starting index</param>
        public virtual void CopyTo(INode[] array, int arrayIndex)
        {
            this._parent.Children_.CopyTo(array, arrayIndex);
            arrayIndex = (arrayIndex + this._parent.Children_.Count);
        }
        
        /// <summary>
        /// Removes the given item from the collection
        /// </summary>
        /// <returns>True, if the item was removed, otherwise False</returns>
        /// <param name="item">The item that should be removed</param>
        public virtual bool Remove(INode item)
        {
            if (this._parent.Children_.Remove(item))
            {
                return true;
            }
            return false;
        }
        
        /// <summary>
        /// Gets an enumerator that enumerates the collection
        /// </summary>
        /// <returns>A generic enumerator</returns>
        public virtual IEnumerator<INode> GetEnumerator()
        {
            return Enumerable.Empty<INode>().Concat(this._parent.Children_).GetEnumerator();
        }
        
        IEnumerator IEnumerable.GetEnumerator()
        {
            return this.GetEnumerator();
        }
        
        /// <summary>
        /// Gets the index of the given element
        /// </summary>
        /// <returns>The index of the given element or -1 if it was not found</returns>
        /// <param name="item">The item that should be looked for</param>
        public virtual int IndexOf(INode item)
        {
            int runningIndex = 0;
            int index;
            index = this._parent.Children_.IndexOf(item);
            if ((index == -1))
            {
                runningIndex = (runningIndex + this._parent.Children_.Count);
            }
            else
            {
                return (index + runningIndex);
            }
            return -1;
        }
        
        /// <summary>
        /// Inserts the given item at the given index of the collection
        /// </summary>
        /// <param name="index">The index where to add the item</param>
        /// <param name="item">The item that should be added</param>
        public virtual void Insert(int index, INode item)
        {
            int runningIndex = 0;
            if ((this._parent.Children_.Count 
                        <= (index - runningIndex)))
            {
                this._parent.Children_.Insert((index - runningIndex), item);
                return;
            }
            else
            {
                runningIndex = (runningIndex + this._parent.Children_.Count);
            }
            throw new ArgumentOutOfRangeException("index");
        }
        
        /// <summary>
        /// Removes the item at the given position
        /// </summary>
        /// <param name="index">The index where to remove the item</param>
        public virtual void RemoveAt(int index)
        {
            int runningIndex = 0;
            if ((this._parent.Children_.Count 
                        <= (index - runningIndex)))
            {
                this._parent.Children_.RemoveAt((index - runningIndex));
                return;
            }
            else
            {
                runningIndex = (runningIndex + this._parent.Children_.Count);
            }
            throw new ArgumentOutOfRangeException("index");
        }
        
        /// <summary>
        /// Gets an observable version of this collection
        /// </summary>
        public virtual INotifyCollection<INode> AsNotifiable()
        {
            return this.WithUpdates();
        }
        
        /// <summary>
        /// Gets an observable version of this collection
        /// </summary>
        INotifyEnumerable<INode> IEnumerableExpression<INode>.AsNotifiable()
        {
            return this.WithUpdates();
        }
        
        /// <summary>
        /// Gets an observable version of this collection
        /// </summary>
        INotifyEnumerable IEnumerableExpression.AsNotifiable()
        {
            return this.WithUpdates();
        }
        
        /// <summary>
        /// Attaches this collection class
        /// </summary>
        public void Attach()
        {
        }
        
        /// <summary>
        /// Detaches this collection class
        /// </summary>
        public void Detach()
        {
        }
    }
    
    /// <summary>
    /// The public interface for Concrete
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(Concrete))]
    [XmlDefaultImplementationTypeAttribute(typeof(Concrete))]
    [ModelRepresentationClassAttribute("http://example.com/refines#//Concrete")]
    public partial interface IConcrete : IModelElement, IBase
    {
        
        /// <summary>
        /// The item property
        /// </summary>
        [DisplayNameAttribute("item")]
        [CategoryAttribute("Concrete")]
        [XmlElementNameAttribute("item")]
        [XmlAttributeAttribute(true)]
        INode Item
        {
            get;
            set;
        }
        
        /// <summary>
        /// The children property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("children")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [ConstantAttribute()]
        IOrderedSetExpression<INode> Children_
        {
            get;
        }
    }
    
    /// <summary>
    /// The public interface for Base
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(Base))]
    [XmlDefaultImplementationTypeAttribute(typeof(Base))]
    [ModelRepresentationClassAttribute("http://example.com/refines#//Base")]
    public partial interface IBase : IModelElement
    {
        
        /// <summary>
        /// The item property
        /// </summary>
        [DisplayNameAttribute("item")]
        [CategoryAttribute("Base")]
        [XmlElementNameAttribute("item")]
        [XmlAttributeAttribute(true)]
        INode Item
        {
            get;
            set;
        }
        
        /// <summary>
        /// The children property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("children")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [ConstantAttribute()]
        IListExpression<INode> Children_
        {
            get;
        }
    }
    
    /// <summary>
    /// The public interface for Node
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(Node))]
    [XmlDefaultImplementationTypeAttribute(typeof(Node))]
    [ModelRepresentationClassAttribute("http://example.com/refines#//Node")]
    public partial interface INode : IModelElement
    {
        
        /// <summary>
        /// The name property
        /// </summary>
        [DisplayNameAttribute("name")]
        [CategoryAttribute("Node")]
        [XmlElementNameAttribute("name")]
        [IdAttribute()]
        [XmlAttributeAttribute(true)]
        string Name
        {
            get;
            set;
        }
    }
}
